### PR TITLE
Update get.html

### PR DESCRIPTION
**Pull request by TutlaMC**
fast lmao

### CODE REVIEW

**Comment by ashishagarwal2023** [comment]
Bro does PR on every commits

**Comment by ashishagarwal2023** [comment]
Avg commit grinder

**Comment by TutlaMC** [comment]
No it had a mistake to fix so I merged it into the PR

**Comment by ashishagarwal2023** [comment]
image
average blind u can use just javascript and do not remove the a element that  u clicked, the document.body.innerHTML+= has invalid syntax (no quotes after href no space even)

**Comment by ashishagarwal2023** [comment]
+ why a  download attribute

**Comment by ashishagarwal2023** [comment]
yyeahh lmao

**Pull request closed without merging**
