### PR TITLE
Full Website Revamp

### PR DESCRIPTION
**Pull request by TutlaMC**
- New Navbar & Footer and a new system
- All Pages have been revamped
- Removal of wiki
- Config System
- Archived AI
- SEO Updated
- josh's existence has been removed
- Projects page added  (suggested by inoam)

It's the new site

### CODE REVIEW

**Comment by thetrouper** [comment]
Great pull request. I think I'll be merging it if @ItziSpyder agrees.

**Comment by I-No-oNe** [comment]
@ItziSpyder How we can fix the conflict?

**Comment by I-No-oNe** [comment]
I have a small PR fix  to @TutlaMC PR, But I need #20 to be merged

**Comment by ashishagarwal2023** [comment]
image

Nice I loved it. What a SEO!

image
Just asking you, 404

**Comment by ashishagarwal2023** [comment]
Well, I don't like bootstrap. Great tho, you are involving into HTML.

**Comment by ashishagarwal2023** [comment]
@ItziSpyder 
image
CSS code..CCS exists. @TutlaMC lmfao

**Comment by ashishagarwal2023** [comment]
- change CSS code to CCS code in homepage
- fix contrast of gallery image-text
- remove or fix fake gallery slideshow left-right buttons
- fix /index/index.css 404
- add padding to body or container
- fix overflow
- fix gallery on gallery page too
- add footer on gallery page
- add min-height to faq to prevent footer & header from moving when u open a faq
- navbar has link "Download" with target to /download.html but it does not take you to download.html (click to download.html, hover and automatically show modrinth/curseforge links)
- fix flashing in download.html
- new line in CCS/CSS code moves the content below it
- ccs codes can be inline (i.e. not be block, both float left-right but they don't go in same Y
- footer's left side is too short, it should have icon. add a contributors page, not directly the list

and yes, the revamp before this...where's me?
- theres a lot thing to do

**Comment by I-No-oNe** [comment]
Stfu and leave @TutlaMC alone

**Comment by TutlaMC** [comment]
@ashishagarwal2023 those problems were caused due to a conflict and have been fixed in the new PR. It was caused due to remnants of your code in it.

**Comment by ashishagarwal2023** [comment]
Oh

**Pull request merged**
